### ISSUE TITLE
Tasks for:  02-02-2017

### ISSUE THREAD

**Issue by sjBao** [nyc-otters-2017/Truthy#12]
- [x] Check-in with instructors about our progress, ask for feedback.

*Because we are all working on the same controller, let's find a way to work on our separate features with out causing commit errors*

- [x] [Blacklisted URLs](https://github.com/nyc-otters-2017/Truthy/issues/8) - @polymer940c 
- [x] [Watson API](https://github.com/nyc-otters-2017/Truthy/issues/9) - @Jefferson-Faseler 
- [ ] [Reverse Image Search](https://github.com/nyc-otters-2017/Truthy/issues/10) - @johntalio 
- [ ] [Author](https://www.google.com)?
- [ ] [Quotes](https://github.com/nyc-otters-2017/Truthy/issues/11)?
